export const hobbyList = [
  { id: 0, type: 'entertainment', title: '영화', isClicked: false },
  { id: 1, type: 'entertainment', title: '드라마', isClicked: false },
  { id: 2, type: 'entertainment', title: '문학/예술', isClicked: false },
  { id: 3, type: 'entertainment', title: '공연/전시', isClicked: false },
  { id: 4, type: 'entertainment', title: '음악', isClicked: false },
  { id: 5, type: 'entertainment', title: '디자인', isClicked: false },
  { id: 6, type: 'sport', title: '러닝/산책', isClicked: false },
  { id: 7, type: 'sport', title: '등산', isClicked: false },
  { id: 8, type: 'sport', title: '축구', isClicked: false },
  { id: 9, type: 'sport', title: '헬스', isClicked: false },
  { id: 10, type: 'sport', title: '클라이밍', isClicked: false },
  { id: 11, type: 'sport', title: '탁구', isClicked: false },
  { id: 12, type: 'sport', title: '스키/보드', isClicked: false },
  { id: 13, type: 'sport', title: '자전거', isClicked: false },
  { id: 14, type: 'sport', title: '서핑', isClicked: false },
  { id: 15, type: 'sport', title: '골프', isClicked: false },
  { id: 16, type: 'sport', title: '테니스', isClicked: false },
  { id: 17, type: 'sport', title: '볼링', isClicked: false },
  { id: 18, type: 'sport', title: '야구', isClicked: false },
  { id: 19, type: 'hobby', title: '요리/베이킹', isClicked: false },
  { id: 20, type: 'hobby', title: '독서', isClicked: false },
  { id: 21, type: 'hobby', title: '게임', isClicked: false },
  { id: 22, type: 'hobby', title: '사진/영상', isClicked: false },
  { id: 23, type: 'hobby', title: '여행', isClicked: false },
  { id: 24, type: 'hobby', title: 'DIY/공예', isClicked: false },
  { id: 25, type: 'study', title: '프로그래밍', isClicked: false },
  { id: 26, type: 'study', title: '외국어', isClicked: false },
  { id: 27, type: 'study', title: '심리학', isClicked: false },
  { id: 28, type: 'study', title: '투자/제테크', isClicked: false },
  { id: 29, type: 'study', title: '자격증', isClicked: false },
  { id: 30, type: 'etc', title: '반려 동물', isClicked: false },
  { id: 31, type: 'etc', title: '환경', isClicked: false },
  { id: 32, type: 'etc', title: '인테리어', isClicked: false },
  { id: 33, type: 'etc', title: '자원봉사', isClicked: false },
];
